global_frame: /map
robot_base_frame: /base_link
update_frequency: 10.0
publish_frequency: 10.0
static_map: false
rolling_window: false
resolution: 0.2
transform_tolerance: 1.0
map_type: costmap
plugins:
      - {name: static_map,       type: "costmap_2d::StaticLayer"}
      - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
      - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}


obstacle_range: 50
raytrace_range: 50
footprint: [[0.075, 0.075], [0.075, -0.075], [-0.075, -0.075], [-0.075, 0.075]]


footprint_padding: 0.1
robot_radius: 1
inflation_layer:  
  enabled: true
  cost_scaling_factor: 2
  inflation_radius: 1
obstacles:
  observation_sources: radar
  radar: {data_type: PointCloud2,topic: /map/map/velody4ne_points, expected_update_rate: 10,
    observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: -0.3}

  observation_sources: mobileye
  mobileye: {data_type: PointCloud2,topic: /map/map/velodyne_po4ints, expected_update_rate: 10,
    observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: -0.3}
  

  

